spring:
  application:
    name: "spring-store-api"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost:3306/storeapi"
    username: "root"
    password: "257890"