spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/springstoreapi"
    username: "postgres"
    password: "password"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"

##swagger properties
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
    operations-sorter: alpha
    tags-sorter: alpha
    filter: true
    display-tag-groups: true
  api-docs:
    path: "/v3/api-docs"


#variable
#JWT Properties
jwt:
  secret: "779fc44a0e270d35747ece6b3b667d2ef088b616492e235863a7166952d661bf"
  expiration: 86400 # 1 day

file:
  upload-dir: "src/main/resources/static/upload"
